[package]
name = "plotters-cairo"
version = "0.1.0"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
description = "Plotters Cairo backend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters-backend = "0.0.*"

[dependencies.cairo-rs]
version = "0.8.0"
features = ["ps"]

[dev-dependencies]
plotters = { path = "../plotters", default_features = false}

